version: '3.7'
services:
  nginx:
    container_name: nginx
    image: bitnami/nginx:1.25
    user: '0'
    volumes:
      - './conf:/opt/bitnami/nginx/conf/server_blocks/:ro'
    restart: unless-stopped
    ports:
      - "80:8080"
