version: '3.0'
services:
  clickhouse:
    image: bitnami/clickhouse
    container_name: clickhouse
    restart: always
    environment:
      - CLICKHOUSE_ADMIN_USER=default
      - CLICKHOUSE_ADMIN_PASSWORD=pro@ClicKhouse
    volumes:
      - 'clickhouse-storage:/bitnami/clickhouse'
      - './conf:/bitnami/clickhouse/etc/conf.d'
    ports:
      - '9000:9000'
      - '8123:8123'

volumes:
  clickhouse-storage:


