version: '3'

services:
  redis:
    image: 'registry:2'
    restart: always
    environment:
      - REGISTRY_HTTP_ADDR=0.0.0.0:5000
    volumes:
      - registry-data:/var/lib/registry
    ports:
      - '5000:5000'


volumes:
  registry-data: